Homework6
Artemzhi38/EPAM_homework pull request #7
Opened 2021-09-26 17:07 UTC by Artemzhi38

2021-09-27 20:22 UTC, nikitosboroda requested changes

2021-09-27 20:22 UTC, icanhardcode commented on homeworks/homework6/task1.py
> +    def get_created_instances(_=None):
wtf? if u dont need any params - dont write anything

2021-09-27 20:22 UTC, nikitosboroda commented on homeworks/homework6/task2.py
> +        if homework is None:
remember how to write conditions in python

2021-10-10 19:58 UTC, nikitosboroda requested changes

2021-10-10 19:58 UTC, nikitosboroda commented on homeworks/homework6/task1.py
> +    instance = 0
should be a class attribute (static)

2021-10-10 19:58 UTC, nikitosboroda commented on homeworks/homework6/task1.py
> +        setattr(self, 'reset_instances_counter', reset_instances_counter)
wrong place

2021-10-10 19:58 UTC, nikitosboroda commented on homeworks/homework6/task2.py
> +        else:
u dont need to write ```else``` if u do ```return``` in ```if``` statement

2021-10-28 17:30 UTC, icanhardcode requested changes

2021-10-28 17:30 UTC, icanhardcode commented on homeworks/homework6/task1.py
> +        setattr(self, 'reset_instances_counter', reset_instances_counter)
look at this

2021-10-28 17:30 UTC, icanhardcode commented on homeworks/homework6/task1.py
> +    setattr(cls, 'reset_instances_counter', reset_instances_counter)
and look at this... these rows are the same.. left only one pair of these.. make a right choice

2021-10-30 22:10 UTC, nikitosboroda approved these changes

2021-10-31 10:17 UTC, merged